_core:
  default_config_hash: IQjf_ytthngZTAk_MU8-74VecArWD3G5g0oEH6PM6GA
toolbar_items:
  - devel.cache_clear
  - devel.container_info.service
  - devel.route_info.item
  - devel.admin_settings_link
  - devel.event_info
  - devel_php.execute_php
  - devel.field_info_page
  - devel.layout_info
  - devel.phpinfo
  - devel.menu_rebuild
  - devel.reinstall
  - devel.route_info
  - devel.run_cron
  - devel.state_system_page
  - devel.switch_user
  - devel.theme_registry
