<?php

/**
 * @file
 * This is the module file for pai_quick_edit.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Impliments hook_form_alter()
 */
function pai_quick_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {

}

/**
 * Processes checkboxes for filtering.
 */
function pai_quick_edit_process_term_checkboxes(&$element, FormStateInterface $form_state, &$complete_form) {

}
