<?php

/**
 * @file
 * This is the module file for pai_utility.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/**
 * Impliments hook_form_alter()
 */
function pai_utility_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == "views_exposed_form") {

    // $view = $form_state->get('view');
    if (isset($form['tid'])) {
      $form['tid']['#process'][] = "pai_utility_process_term_checkboxes";
    }
  }
}

/**
 * Processes checkboxes for filtering.
 */
function pai_utility_process_term_checkboxes(&$element, FormStateInterface $form_state, &$complete_form) {

  foreach (Element::children($element) as $key) {
    $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($key);

    if ($term->hasField('field_theme_slug')) {
      $element[$key]['#wrapper_attributes']['class'][] = "u-tag-theme--" . $term->field_theme_slug->value;
    }
  }

  return $element;
}

/**
 * Impliments hook_entity_type_alter()
 */
function pai_utility_entity_type_alter(&$entity_types) {
  // Override class to change label.
  $entity_types['taxonomy_term']->setClass(\Drupal\pai_utility\Entity\TaxonomyTerm::class);
}
