_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  breakpoint: 0
  charts: 0
  charts_billboard: 0
  charts_c3: 0
  charts_chartjs: 0
  ckeditor5: 0
  color_field: 0
  config: 0
  config_inspector: 0
  config_split: 0
  contextual: 0
  crop: 0
  datalayer: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  editoria11y: 0
  entity_browser: 0
  entity_reference_revisions: 0
  entity_usage: 0
  esm_site: 0
  esm_test_base: 0
  esm_test_blc: 0
  esm_test_html_val: 0
  esm_test_lighthouse: 0
  esm_test_pchr: 0
  esm_test_result_base: 0
  esm_test_tag_checker: 0
  esm_test_wpt: 0
  esm_url_group: 0
  external_site_monitor: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  gin_login: 0
  gin_toolbar: 0
  google_tag: 0
  help: 0
  highlightjs_input_filter: 0
  image: 0
  imagick: 0
  img_processor: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_draggable: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  key: 0
  key_auth: 0
  key_value_field: 0
  language: 0
  layout_discovery: 0
  layout_paragraphs: 0
  layout_paragraphs_library: 0
  link: 0
  media: 0
  media_bulk_upload: 0
  media_bulk_upload_dropzonejs: 0
  media_library: 0
  menu_item_extras: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  multivalue_form_element: 0
  mysql: 0
  node: 0
  node_revision_delete: 0
  options: 0
  other_view_filter: 0
  page_cache: 0
  pai_admin_mod: 0
  pai_redirect: 0
  pai_utility: 0
  pantheon_advanced_page_cache: 0
  paragraphs_library: 0
  path: 0
  path_alias: 0
  phpass: 0
  queue_ui: 0
  recreate_block_content: 0
  redirect: 0
  redirect_404: 0
  redis: 0
  responsive_image: 0
  save_edit: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_db: 0
  search_api_pantheon: 0
  search_api_pantheon_admin: 0
  search_api_solr: 0
  search_api_solr_admin: 0
  search_api_solr_autocomplete: 0
  search_api_solr_devel: 0
  shortcut: 0
  simple_block: 0
  simple_sitemap: 0
  standard: 0
  system: 0
  taxonomy: 0
  text: 0
  timing_monitor: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  ultimate_cron: 0
  update: 0
  user: 0
  views_ajax_history: 0
  views_bulk_operations: 0
  views_ui: 0
  viewsreference: 0
  vis_reg_result: 0
  workflows: 0
  pathauto: 1
  selective_better_exposed_filters: 1
  views: 10
  paragraphs: 11
theme:
  olivero: 0
  claro: 0
  gin: 0
  stable9: 0
  pai: 0
  pai_admin: 0
profile: standard
