_core:
  default_config_hash: WInQy4-vMjoCIjxls-kjZ9ivcQ2DCcdOrx8SxehGv-k
add_page_meta: true
output_terms: true
output_fields: false
remove_from_admin_routes: true
lib_helper: false
entity_meta:
  created: '0'
  langcode: '0'
  name: '0'
  status: '0'
  uid: '0'
  uuid: '0'
  vid: '0'
enable_ia: true
ia_depth: 3
ia_category_primary: primaryCategory
ia_category_sub: subCategory
vocabs:
  clients: clients
  tags: tags
  tech: tech
  icons: '0'
  media_tags: '0'
expose_user_details: ''
expose_user_details_roles:
  authenticated: '0'
  content_editor: '0'
  administrator: '0'
current_user_meta:
  name: name
  roles: roles
  mail: '0'
  created: '0'
  access: '0'
group: false
expose_user_details_fields: false
entity_title: entityTitle
entity_type: entityType
entity_bundle: entityBundle
entity_identifier: entityId
group_label: groupLabel
drupal_language: drupalLanguage
drupal_country: drupalCountry
site_name: siteName
key_replacements:
  - ''
