cloneable_entities:
  - block
  - block_content
  - block_content_type
  - config_split
  - crop
  - crop_type
  - editor
  - editor_note
  - entity_browser
  - site
  - test
  - test_type
  - result_type
  - result
  - url_group
  - field_config
  - field_storage_config
  - file
  - filter_format
  - google_tag_container
  - image_style
  - key
  - key_config_override
  - configurable_language
  - language_content_settings
  - media_type
  - media
  - media_bulk_config
  - menu_link_content
  - metatag_defaults
  - node_type
  - node
  - paragraphs_library_item
  - path_alias
  - redirect
  - responsive_image_style
  - search_api_server
  - search_api_index
  - search_api_task
  - search_api_autocomplete_search
  - solr_cache
  - solr_field_type
  - solr_request_dispatcher
  - solr_request_handler
  - shortcut_set
  - shortcut
  - simple_block
  - simple_sitemap_type
  - simple_sitemap
  - action
  - menu
  - taxonomy_term
  - taxonomy_vocabulary
  - tour
  - ultimate_cron_job
  - user
  - user_role
  - vis_reg_result
  - workflow
  - pathauto_pattern
  - view
  - paragraph
  - paragraphs_type
  - date_format
  - entity_form_mode
  - entity_view_display
  - entity_form_display
  - entity_view_mode
  - base_field_override
