_core:
  default_config_hash: aeLZKJyeLp_HASU7e3edM-S5x0h6zf-_ymLvtFXhDPk
branch: develop
api_url: 'https://api.github.com/repos/pingevt/pai23/actions/workflows/62231011/dispatches'
github_token: github_auth
dir: 'public://tests/pchr-reports'
dependencies:
  enforced:
    module:
      - esm_test_pchr
