_core:
  default_config_hash: U4NZcFKrha4kb2NjttTwfFhMoq7vGRxCbSLduDI2TrM
branch: main
api_url: 'https://api.github.com/repos/pingevt/external_site_monitor_ghactions/actions/workflows/51619225/dispatches'
github_token: github_auth
dir: 'public://tests/lighthouse-reports'
dependencies:
  enforced:
    module:
      - esm_test_lighthouse
