_core:
  default_config_hash: U4NZcFKrha4kb2NjttTwfFhMoq7vGRxCbSLduDI2TrM
branch: develop
api_url: 'https://api.github.com/repos/pingevt/pai23/actions/workflows/62231012/dispatches'
github_token: github_auth
dir: 'public://tests/lighthouse-reports'
dependencies:
  enforced:
    module:
      - esm_test_lighthouse
