features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 0
  path: 'public://admin-favicon.ico'
  mimetype: image/vnd.microsoft.icon
enable_darkmode: '0'
preset_accent_color: custom
accent_color: '#993333'
preset_focus_color: gin
focus_color: ''
high_contrast_mode: 0
classic_toolbar: horizontal
secondary_toolbar_frontend: 0
layout_density: ''
show_description_toggle: 0
show_user_theme_settings: 0
