_core:
  default_config_hash: MfCIGqpPS5Ihe_IOWhqbB1hDemb6VF_186BxkS8Giwg
button_value: 'Save & Edit'
button_weight: '-1'
gin_primary: false
unpublish: false
unpublish_new_only: false
hide_default_save: false
hide_default_publish: false
hide_default_preview: false
hide_default_delete: false
enable_node_types_automatically: false
node_types:
  article: article
  page: page
  project: project
  project_series: project_series
